log-level: INFO

server:
  port: 8108

kafka:
  brokers:
    - "cuktjh76hfisn32fck4g.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092"
  topic: "web-crawler"
  group-id: "shoppin-web-crawler"
  auto-offset-reset: "earliest"
  username: webcrawler
  password: "webcrawler"